name: Auth Service CI

on:
  push:
    branches: [main]
    paths:
      - 'packages/auth/**'
      - '.github/workflows/ci-auth.yml'
  pull_request:
    branches: [main]
    paths:
      - 'packages/auth/**'
      - '.github/workflows/ci-auth.yml'

jobs:
  auth:
    name: Auth Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/auth
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: packages/auth/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
