name: Monorepo CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  auth:
    name: Auth Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auth
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: auth/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

  todos:
    name: Todos Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todos
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: todos/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
